apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-node
  name: hello-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-node
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
        - image: localhost:5000/node-server
          name: server
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
